/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/releases")
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/groups/public/")
    }

    maven {
        url = uri("https://repo.mikeprimm.com/")
    }

    maven {
        url = uri("https://repo.wertarbyte.com")
    }

    maven {
        url = uri("file://C:/Dev/Minecraft/ChunkyMapFabric/lib")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.se.llbit.chunky.core)
    api(libs.org.apache.commons.commons.math3)
    api(libs.com.squareup.okhttp3.okhttp)
    api(libs.com.google.code.gson.gson)
    api(libs.net.time4tea.oidnjni)
    api(libs.org.jetbrains.kotlin.kotlin.stdlib)
    api(libs.de.lemaik.chunky.denoiser)
    compileOnly(libs.org.bukkit.bukkit)
    compileOnly(libs.us.dynmap.dynmapcoreapi)
}

group = "de.lemaik.chunkymap"
version = "2.5.2"
description = "ChunkyMap"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
